# Generated by Django 5.0.2 on 2024-02-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='user',
            new_name='username',
        ),
    ]
